import pandas as pd
import re

# 读取原始Excel文件（请确保文件路径正确）
file_path = 'Pollutant Experimental Data.xlsx'  # 替换为您的实际文件路径
df = pd.read_excel(file_path, sheet_name='Sheet1')

# 1. 污染物类型 中英文映射字典（根据您的数据整理）
pollutant_mapping = {
    '氯乙烯': 'Vinyl chloride',
    '1,1-二氯乙烯': '1,1-Dichloroethylene',
    '二氯甲烷': 'Dichloromethane',
    '反-1,2-二氯乙烯': 'trans-1,2-Dichloroethylene',
    '1,1-二氯乙烷': '1,1-Dichloroethane',
    '顺-1,2-二氯乙烯': 'cis-1,2-Dichloroethylene',
    '氯仿': 'Chloroform',
    '1,1,1-三氯乙烷': '1,1,1-Trichloroethane',
    '四氯化碳': 'Carbon tetrachloride',
    '1,2-二氯乙烷': '1,2-Dichloroethane',
    '苯': 'Benzene',
    '三氯乙烯': 'Trichloroethylene',
    '1,1,2-三氯乙烷': '1,1,2-Trichloroethane',
    '四氯乙烯': 'Tetrachloroethylene',
    '氯苯': 'Chlorobenzene',
    '1,1,2,2-四氯乙烷': '1,1,2,2-Tetrachloroethane',
    '正己烷': 'n-Hexane',
    '苯乙烯': 'Styrene',
    '甲苯': 'Toluene',
    '乙酸乙酯': 'Ethyl acetate',
    '磷酸三丁酯': 'Tributyl phosphate',
    '乙苯': 'Ethylbenzene',
    '二甲苯': 'Xylene',
    '对二甲苯': 'p-Xylene',
    '间二甲苯': 'm-Xylene',
    '邻二甲苯': 'o-Xylene',
    'BTEX': 'BTEX',
    '苯胺': 'Aniline',
    '苯酚': 'Phenol',
    '甲醇': 'Methanol',
    '乙醇': 'Ethanol',
    '异丙醇': 'Isopropanol',
    '甲基丙烯酸甲酯': 'Methyl methacrylate',
    '正己烷': 'n-Hexane',
    'α-蒎烯': 'α-Pinene',
    '己烷': 'Hexane',
    '乙醛': 'Acetaldehyde',
    'N,N-二甲基乙酰胺': 'N,N-Dimethylacetamide',
    '对乙酰氨基酚': 'Acetaminophen',
    '邻氯甲苯': 'o-Chlorotoluene',
    '甲基橙': 'Methyl orange',
    '亚甲基蓝': 'Methylene blue',
    '罗丹明B': 'Rhodamine B',
    '二甲基亚砜': 'Dimethyl sulfoxide',
    'N-甲基吡咯烷酮': 'N-Methylpyrrolidone',
    '氯化钠': 'Sodium chloride',
    '氯苯': 'Chlorobenzene',  # 重复项确保覆盖
    '苯乙烯': 'Styrene',
    '甲苯': 'Toluene',
    '乙苯': 'Ethylbenzene',
    '二甲苯': 'Xylene',
    '乙酸乙酯': 'Ethyl acetate',
    '正己烷': 'n-Hexane',
    '二氯甲烷': 'Dichloromethane',
    '1,1-二氯乙烷': '1,1-Dichloroethane',
    '顺-1,2-二氯乙烯': 'cis-1,2-Dichloroethylene',
    '反-1,2-二氯乙烯': 'trans-1,2-Dichloroethylene',
    '1,1,1-三氯乙烷': '1,1,1-Trichloroethane',
    '1,2-二氯乙烷': '1,2-Dichloroethane',
    '1,1,2-三氯乙烷': '1,1,2-Trichloroethane',
    '1,1,2,2-四氯乙烷': '1,1,2,2-Tetrachloroethane',
    '四氯乙烯': 'Tetrachloroethylene',
    '三氯乙烯': 'Trichloroethylene',
    '氯仿': 'Chloroform',
    '四氯化碳': 'Carbon tetrachloride',
    '苯': 'Benzene',
    '甲苯': 'Toluene',
    '乙苯': 'Ethylbenzene',
    '二甲苯': 'Xylene',
    '氯苯': 'Chlorobenzene',
    '苯乙烯': 'Styrene',
    '乙酸乙酯': 'Ethyl acetate',
    '磷酸三丁酯': 'Tributyl phosphate',
    '正己烷': 'n-Hexane',
    '二氯甲烷': 'Dichloromethane',
    '甲基丙烯酸甲酯': 'Methyl methacrylate',
    '苯胺': 'Aniline',
    '苯酚': 'Phenol',
    '甲醇': 'Methanol',
    '乙醇': 'Ethanol',
    '异丙醇': 'Isopropanol',
    '对乙酰氨基酚': 'Acetaminophen',
    '邻氯甲苯': 'o-Chlorotoluene',
    'α-蒎烯': 'α-Pinene',
    '己烷': 'Hexane',
    '乙醛': 'Acetaldehyde',
    'N,N-二甲基乙酰胺': 'N,N-Dimethylacetamide',
    '二甲基亚砜': 'Dimethyl sulfoxide',
    'N-甲基吡咯烷酮': 'N-Methylpyrrolidone',
    '氯化钠': 'Sodium chloride',
    '甲基橙': 'Methyl orange',
    '亚甲基蓝': 'Methylene blue',
    '罗丹明B': 'Rhodamine B'
}

# 对于未在字典中的污染物，保留原值（或可以调用翻译API，这里简单保留）
def translate_pollutant(chinese):
    return pollutant_mapping.get(chinese, chinese)

# 2. 营养条件 翻译函数（将中文描述转换为英文）
def translate_nutrient_condition(text):
    if not isinstance(text, str):
        return text
    # 常见术语映射
    replacements = {
        '总溶解固体': 'Total Dissolved Solids (TDS)',
        '电导率': 'Conductivity',
        '溶解氧': 'Dissolved Oxygen (DO)',
        '氮浓度': 'Nitrogen concentration',
        '营养液': 'Nutrient solution',
        '特定培养基': 'Specific medium',
        '合成废水': 'Synthetic wastewater',
        '超纯水': 'Ultrapure water',
        '实际地下水': 'Actual groundwater',
        '实验室配制的BTEX废水': 'Lab-prepared BTEX wastewater',
        '含苯、甲苯、乙苯、二甲苯各20 mg/L': 'containing 20 mg/L each of benzene, toluene, ethylbenzene, xylene',
        '葡萄糖8 g/L': 'glucose 8 g/L',
        '酒石酸铵3.3 g/L': 'ammonium tartrate 3.3 g/L',
        '琥珀酸二甲酯1.68 g/L': 'dimethyl succinate 1.68 g/L',
        '微量营养素': 'micronutrients',
        '大量营养素': 'macronutrients',
        '漆酶溶液': 'laccase solution',
        '无介体': 'without mediator',
        'ABTS介体': 'ABTS mediator',
        'CYP450抑制剂ABT': 'CYP450 inhibitor ABT',
        '无抑制剂': 'without inhibitor',
        '滴流床反应器实验组': 'trickle bed reactor experimental group',
        '热灭活对照': 'heat-inactivated control',
        '非生物对照': 'abiotic control',
        '质量平衡降解贡献': 'mass balance degradation contribution',
        'Fe³⁺/PMS/MoS₂体系': 'Fe³⁺/PMS/MoS₂ system',
        '空气鼓泡': 'air bubbling',
        '纯水吸收': 'pure water absorption',
        'MoS₂体系（无PMS）': 'MoS₂ system (without PMS)',
        'Fe³⁺/PMS体系': 'Fe³⁺/PMS system',
        'MoS₂/PMS体系': 'MoS₂/PMS system',
        'Fe²⁺/PMS体系': 'Fe²⁺/PMS system',
        'Fe²⁺/PMS/MoS₂体系': 'Fe²⁺/PMS/MoS₂ system',
        '添加30 mM TBA': 'with 30 mM TBA',
        '添加30 mM EtOH': 'with 30 mM EtOH',
        '添加50 mM TBA': 'with 50 mM TBA',
        '添加50 mM EtOH': 'with 50 mM EtOH',
        'N₂鼓泡': 'N₂ bubbling',
        '添加15 U/mL SOD': 'with 15 U/mL SOD',
        '添加30 U/mL SOD': 'with 30 U/mL SOD',
        '添加50 U/mL SOD': 'with 50 U/mL SOD',
        '添加TEMP': 'with TEMP',
        '营养液 A，30 毫升/2 小时，EBRT 71 秒': 'Nutrient solution A, 30 mL/2 h, EBRT 71 s',
        '营养液 A，30 毫升/2 小时，EBRT 70 秒': 'Nutrient solution A, 30 mL/2 h, EBRT 70 s',
        '营养液 A，EBRT71 秒、57 秒、43 秒，入口浓度 300–900 mg/m³': 'Nutrient solution A, EBRT 71 s, 57 s, 43 s, inlet concentration 300–900 mg/m³',
        '营养液 A，EBRT 34 秒，入口浓度 900 mg/m³': 'Nutrient solution A, EBRT 34 s, inlet concentration 900 mg/m³',
        '进气口 28.5 秒，入口浓度 300–630 mg/m³，饥饿 15 天': 'Inlet 28.5 s, inlet concentration 300–630 mg/m³, starvation 15 days',
        '昆虫幼虫接种，EBRT 34 秒，入口浓度 300–630 mg/m³': 'Insect larvae inoculation, EBRT 34 s, inlet concentration 300–630 mg/m³',
        'FeS/H₂O₂体系': 'FeS/H₂O₂ system',
        'Fe(II)/H₂O₂体系': 'Fe(II)/H₂O₂ system',
        'H₂O₂单独体系': 'H₂O₂ alone system',
        'FeS单独体系': 'FeS alone system',
        'H₂O₂一次投加20 mM': 'H₂O₂ single addition 20 mM',
        'H₂O₂间歇投加': 'H₂O₂ intermittent addition',
        '气流速0.5 L/min': 'gas flow rate 0.5 L/min',
        '气流速1.0 L/min': 'gas flow rate 1.0 L/min',
        '气流速1.5 L/min': 'gas flow rate 1.5 L/min',
        '苯乙烯初始浓度30 ppmv': 'initial styrene concentration 30 ppmv',
        '苯乙烯初始浓度50 ppmv': 'initial styrene concentration 50 ppmv',
        '苯乙烯初始浓度70 ppmv': 'initial styrene concentration 70 ppmv',
        '苯乙烯初始浓度100 ppmv': 'initial styrene concentration 100 ppmv',
        'Cl⁻浓度': 'Cl⁻ concentration',
        'CO₃²⁻浓度': 'CO₃²⁻ concentration',
        '添加TBA 5 mM': 'with 5 mM TBA',
        'FeNPs-叶投加量': 'FeNPs-leaf dosage',
        'FeNPs-果皮投加量': 'FeNPs-peel dosage',
        'FeNPs-种子投加量': 'FeNPs-seed dosage',
        'CoFe₂O₄/MoS₂/PMS湿式洗涤塔系统': 'CoFe₂O₄/MoS₂/PMS wet scrubber system',
        '含30 ppm甲苯气体、2 g/L PMS、0.1 g/L催化剂': 'containing 30 ppm toluene gas, 2 g/L PMS, 0.1 g/L catalyst',
        '连续反应8 h': 'continuous reaction 8 h',
        'UV/过一硫酸盐 (PMS)': 'UV/peroxymonosulfate (PMS)',
        'UV/过硫酸盐 (PDS)': 'UV/persulfate (PDS)',
        '热/过硫酸盐 (PDS)': 'thermal/persulfate (PDS)',
        'Fe²⁺/柠檬酸/过硫酸盐 (PDS)': 'Fe²⁺/citric acid/persulfate (PDS)',
        'UV/过硫酸盐/高锰酸钾 (UV/PDS/KMnO₄)': 'UV/persulfate/potassium permanganate (UV/PDS/KMnO₄)',
        '连续流微泡反应器/过一硫酸盐 (CFS/PMS)': 'continuous flow microbubble reactor/peroxymonosulfate (CFS/PMS)',
        'MIL-101(Fe, Cu)/过硫酸盐 (PDS)': 'MIL-101(Fe, Cu)/persulfate (PDS)',
        'CoFe₂O₄/MoS₂/过一硫酸盐 (PMS)': 'CoFe₂O₄/MoS₂/peroxymonosulfate (PMS)',
        'MoS₂/Fe³⁺/过一硫酸盐 (PMS)': 'MoS₂/Fe³⁺/peroxymonosulfate (PMS)',
        'CoS/多孔石墨化碳/过一硫酸盐 (CoS/PGC/PMS)': 'CoS/porous graphitized carbon/peroxymonosulfate (CoS/PGC/PMS)',
        '放电电压22 kV': 'discharge voltage 22 kV',
        '气体流速0.2 m/s': 'gas flow rate 0.2 m/s',
        '气体流速1.0 m/s': 'gas flow rate 1.0 m/s',
        '初始浓度180 mg/m³': 'initial concentration 180 mg/m³',
        '放电距离20 mm': 'discharge distance 20 mm',
        '放电距离30 mm': 'discharge distance 30 mm',
        '液体流速20 mL/min': 'liquid flow rate 20 mL/min',
        '液体流速30 mL/min': 'liquid flow rate 30 mL/min',
        '液体流速40 mL/min': 'liquid flow rate 40 mL/min',
        '正向进气 (电压12 kV)': 'forward gas inlet (voltage 12 kV)',
        '反向进气 (电压12 kV)': 'reverse gas inlet (voltage 12 kV)',
        '正向进气 (电压20 kV)': 'forward gas inlet (voltage 20 kV)',
        '反向进气 (电压20 kV)': 'reverse gas inlet (voltage 20 kV)',
        '芬顿试剂 (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L, pH 3) + 放电电压12 kV': 'Fenton reagent (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L, pH 3) + discharge voltage 12 kV',
        '芬顿试剂 (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L, pH 3) + 放电电压20 kV': 'Fenton reagent (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L, pH 3) + discharge voltage 20 kV',
        '芬顿试剂 (H₂O₂ 6 mL/L, pH 3) + Fe²⁺浓度0.5 g/L': 'Fenton reagent (H₂O₂ 6 mL/L, pH 3) + Fe²⁺ concentration 0.5 g/L',
        '芬顿试剂 (H₂O₂ 6 mL/L, pH 3) + Fe²⁺浓度2.0 g/L': 'Fenton reagent (H₂O₂ 6 mL/L, pH 3) + Fe²⁺ concentration 2.0 g/L',
        '芬顿试剂 (H₂O₂ 6 mL/L, pH 3) + Fe²⁺浓度2.5 g/L': 'Fenton reagent (H₂O₂ 6 mL/L, pH 3) + Fe²⁺ concentration 2.5 g/L',
        '芬顿试剂 (Fe²⁺ 2.0 g/L, pH 3) + H₂O₂浓度0 mL/L': 'Fenton reagent (Fe²⁺ 2.0 g/L, pH 3) + H₂O₂ concentration 0 mL/L',
        '芬顿试剂 (Fe²⁺ 2.0 g/L, pH 3) + H₂O₂浓度8 mL/L': 'Fenton reagent (Fe²⁺ 2.0 g/L, pH 3) + H₂O₂ concentration 8 mL/L',
        '芬顿试剂 (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L) + pH 2': 'Fenton reagent (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L) + pH 2',
        '芬顿试剂 (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L) + pH 3': 'Fenton reagent (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L) + pH 3',
        '芬顿试剂 (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L) + pH 6': 'Fenton reagent (Fe²⁺ 2.0 g/L, H₂O₂ 6 mL/L) + pH 6',
        '过硫酸盐缓释颗粒 (PS/石蜡质量比3/1) + 100 mg/L Fe²⁺, 流速0.4 mL/min, 第1-3天': 'persulfate sustained-release pellets (PS/paraffin mass ratio 3/1) + 100 mg/L Fe²⁺, flow rate 0.4 mL/min, days 1-3',
        '过硫酸盐缓释颗粒 (PS/石蜡质量比3/1) + 100 mg/L Fe²⁺, 流速0.4 mL/min, 第4-7天': 'persulfate sustained-release pellets (PS/paraffin mass ratio 3/1) + 100 mg/L Fe²⁺, flow rate 0.4 mL/min, days 4-7',
        'Ag/HAP-BpH-6催化剂': 'Ag/HAP-BpH-6 catalyst',
        'Ag/HAP-BpH-8催化剂': 'Ag/HAP-BpH-8 catalyst',
        'Ag/HAP-BpH-10催化剂': 'Ag/HAP-BpH-10 catalyst',
        'Ag/HAP-BpH-11催化剂': 'Ag/HAP-BpH-11 catalyst',
        'BPEC-光系统 (生物阳极+TiO₂光电极，PVDF膜，500Ω外阻)': 'BPEC-photo system (bioanode + TiO₂ photoelectrode, PVDF membrane, 500 Ω external resistance)',
        'MFC-光系统 (生物阳极+碳纤维布阴极，PVDF膜，500Ω外阻)': 'MFC-photo system (bioanode + carbon cloth cathode, PVDF membrane, 500 Ω external resistance)',
        'BPEC-暗系统 (生物阳极+TiO₂光电极，PVDF膜，500Ω外阻)': 'BPEC-dark system (bioanode + TiO₂ photoelectrode, PVDF membrane, 500 Ω external resistance)',
        '光催化系统 (仅阳极液+TiO₂光电极，PVDF膜，500Ω外阻)': 'photocatalytic system (only anolyte + TiO₂ photoelectrode, PVDF membrane, 500 Ω external resistance)',
        'MFC-暗系统 (生物阳极+碳纤维布阴极，PVDF膜，500Ω外阻)': 'MFC-dark system (bioanode + carbon cloth cathode, PVDF membrane, 500 Ω external resistance)',
        'BPEC-光系统 (生物阳极+TiO₂光电极，PVDF膜，200Ω外阻)': 'BPEC-photo system (bioanode + TiO₂ photoelectrode, PVDF membrane, 200 Ω external resistance)',
        'BPEC-光系统 (生物阳极+TiO₂光电极，PVDF膜，1000Ω外阻)': 'BPEC-photo system (bioanode + TiO₂ photoelectrode, PVDF membrane, 1000 Ω external resistance)',
        'BPEC-光系统 (生物阳极+TiO₂光电极，PEM膜，500Ω外阻)': 'BPEC-photo system (bioanode + TiO₂ photoelectrode, PEM membrane, 500 Ω external resistance)',
        'BTF1对照，无Tween 20，进气浓度100 mg/m³，EBRT 60 s，第25天': 'BTF1 control, no Tween 20, inlet concentration 100 mg/m³, EBRT 60 s, day 25',
        'BTF2添加Tween 20 (30 mg/L)，进气浓度100 mg/m³，EBRT 60 s，第26天': 'BTF2 with Tween 20 (30 mg/L), inlet concentration 100 mg/m³, EBRT 60 s, day 26',
        'BTF1对照，无Tween 20，进气浓度300 mg/m³，EBRT 60 s，第59天': 'BTF1 control, no Tween 20, inlet concentration 300 mg/m³, EBRT 60 s, day 59',
        'BTF2添加Tween 20 (30 mg/L)，进气浓度300 mg/m³，EBRT 60 s，第59天': 'BTF2 with Tween 20 (30 mg/L), inlet concentration 300 mg/m³, EBRT 60 s, day 59',
        'BTF1对照，无Tween 20，进气浓度300 mg/m³，EBRT 40 s，稳定期': 'BTF1 control, no Tween 20, inlet concentration 300 mg/m³, EBRT 40 s, steady state',
        'BTF1对照，无Tween 20，进气浓度300 mg/m³，EBRT 20 s，稳定期': 'BTF1 control, no Tween 20, inlet concentration 300 mg/m³, EBRT 20 s, steady state',
        'BTF1对照，无Tween 20，进气浓度300 mg/m³，EBRT 10 s，稳定期': 'BTF1 control, no Tween 20, inlet concentration 300 mg/m³, EBRT 10 s, steady state',
        'BTF2添加Tween 20 (30 mg/L)，进气浓度300 mg/m³，EBRT 40 s，稳定期': 'BTF2 with Tween 20 (30 mg/L), inlet concentration 300 mg/m³, EBRT 40 s, steady state',
        'BTF2添加Tween 20 (30 mg/L)，进气浓度300 mg/m³，EBRT 20 s，稳定期': 'BTF2 with Tween 20 (30 mg/L), inlet concentration 300 mg/m³, EBRT 20 s, steady state',
        'BTF2添加Tween 20 (30 mg/L)，进气浓度300 mg/m³，EBRT 10 s，稳定期': 'BTF2 with Tween 20 (30 mg/L), inlet concentration 300 mg/m³, EBRT 10 s, steady state',
        'BTF2添加Tween 20 (30 mg/L)，EBRT 60 s，IL 25.0 g/m³·h': 'BTF2 with Tween 20 (30 mg/L), EBRT 60 s, IL 25.0 g/m³·h',
        'BTF2添加Tween 20 (30 mg/L)，EBRT 60 s，IL 54.4 g/m³·h': 'BTF2 with Tween 20 (30 mg/L), EBRT 60 s, IL 54.4 g/m³·h',
        '菌株 DKR-7': 'Strain DKR-7',
        '菌株 DKR-8': 'Strain DKR-8',
        '菌株 DKR-10': 'Strain DKR-10',
        '菌株 DKR-11': 'Strain DKR-11',
        '菌株 DKR-12': 'Strain DKR-12',
        '菌株 DKR-13': 'Strain DKR-13',
        '菌株 DKR-14': 'Strain DKR-14',
        '菌株 DKR-15': 'Strain DKR-15',
        '菌株 DKR-17': 'Strain DKR-17',
        '菌株 DKR-18': 'Strain DKR-18',
        '菌株 DKR-19': 'Strain DKR-19',
        '菌株 DKR-20': 'Strain DKR-20',
        '菌株 DKR-21': 'Strain DKR-21',
        '菌株 DKR-22': 'Strain DKR-22',
        '菌株 DKR-23': 'Strain DKR-23',
        '菌株 Kor-1': 'Strain Kor-1',
        '菌株 Kor-2': 'Strain Kor-2',
        '菌株 Kor-3': 'Strain Kor-3',
        '菌株 Kor-4': 'Strain Kor-4',
        '菌株 Kor-5': 'Strain Kor-5',
        '菌株 Kor-6': 'Strain Kor-6',
        '菌株 Kor-8': 'Strain Kor-8',
        '菌株 Kor-11': 'Strain Kor-11',
        '菌株 Kor-12': 'Strain Kor-12',
        '菌株 Kor-35': 'Strain Kor-35',
        '菌株 Kor-42': 'Strain Kor-42',
        '菌株 Kor-51': 'Strain Kor-51',
        '菌株 Kor-61': 'Strain Kor-61',
        '菌株 Kor-7': 'Strain Kor-7',
        '菌株 Kor-8 (第二个)': 'Strain Kor-8 (second)',
        '菌株 Kor-9': 'Strain Kor-9',
        '菌株 Korf-18': 'Strain Korf-18',
        '对照微宇宙 (C)': 'Control microcosm (C)',
        '菌群微宇宙 (BS)': 'Microbial community microcosm (BS)',
        '原生生物炭微宇宙 (BC)': 'Raw biochar microcosm (BC)',
        '固定化细菌生物炭微宇宙 (BC-B)': 'Immobilized bacteria biochar microcosm (BC-B)',
        'PAN/PP/PPy膜，pH=1处理，100 ppm苯胺': 'PAN/PP/PPy membrane, pH=1 treatment, 100 ppm aniline',
        'PAN/PP/PPy膜，pH=3处理，100 ppm苯胺': 'PAN/PP/PPy membrane, pH=3 treatment, 100 ppm aniline',
        'PAN/PP/PPy膜，pH=5处理，100 ppm苯胺': 'PAN/PP/PPy membrane, pH=5 treatment, 100 ppm aniline',
        'PAN/PP/PPy膜，pH=7处理，100 ppm苯胺': 'PAN/PP/PPy membrane, pH=7 treatment, 100 ppm aniline',
        'PAN/PP/PPy膜，pH=9处理，100 ppm苯胺': 'PAN/PP/PPy membrane, pH=9 treatment, 100 ppm aniline',
        'PAN/PP/PPy膜，pH=11处理，100 ppm苯胺': 'PAN/PP/PPy membrane, pH=11 treatment, 100 ppm aniline',
        'PAA/PPy/PP膜，3.5 wt% NaCl，50 ppm苯胺': 'PAA/PPy/PP membrane, 3.5 wt% NaCl, 50 ppm aniline',
        'PAA/PPy/PP膜，3.5 wt% NaCl，100 ppm苯胺': 'PAA/PPy/PP membrane, 3.5 wt% NaCl, 100 ppm aniline',
        'PAA/PPy/PP膜，3.5 wt% NaCl，150 ppm苯胺': 'PAA/PPy/PP membrane, 3.5 wt% NaCl, 150 ppm aniline',
        'PAA/PPy/PP膜，3.5 wt% NaCl，200 ppm苯胺': 'PAA/PPy/PP membrane, 3.5 wt% NaCl, 200 ppm aniline',
        'PAA/PPy/PP膜，100 ppm甲醇': 'PAA/PPy/PP membrane, 100 ppm methanol',
        'PAA/PPy/PP膜，100 ppm乙醇': 'PAA/PPy/PP membrane, 100 ppm ethanol',
        'PAA/PPy/PP膜，100 ppm异丙醇': 'PAA/PPy/PP membrane, 100 ppm isopropanol',
        'PAA/PPy/PP膜，100 ppm苯酚': 'PAA/PPy/PP membrane, 100 ppm phenol',
        'PAA/PPy/PP膜，100 ppm苯胺': 'PAA/PPy/PP membrane, 100 ppm aniline',
        'PAA/PPy/PP膜，5 ppm苯酚': 'PAA/PPy/PP membrane, 5 ppm phenol',
        'PAA/PPy/PP膜，10 ppm苯酚': 'PAA/PPy/PP membrane, 10 ppm phenol',
        'PAA/PPy/PP膜，20 ppm苯酚': 'PAA/PPy/PP membrane, 20 ppm phenol',
        'PAA/PPy/PP膜，50 ppm苯酚': 'PAA/PPy/PP membrane, 50 ppm phenol',
        'PAA/PPy/PP膜，100 ppm苯酚': 'PAA/PPy/PP membrane, 100 ppm phenol',
        'PAA/PPy/PP膜，3.5 wt% NaCl': 'PAA/PPy/PP membrane, 3.5 wt% NaCl',
        'PAA/PPy/PP膜，10 wt% NaCl': 'PAA/PPy/PP membrane, 10 wt% NaCl',
        'PAA/PPy/PP膜，20 wt% NaCl': 'PAA/PPy/PP membrane, 20 wt% NaCl',
        'PAA/PPy/PP膜，渤海海水': 'PAA/PPy/PP membrane, Bohai seawater',
        'PAA/PPy/PP膜，浓缩盐水': 'PAA/PPy/PP membrane, concentrated brine',
        'PAA/PPy/PP膜，3.5 wt% NaCl + 100 ppm苯胺，100小时稳定': 'PAA/PPy/PP membrane, 3.5 wt% NaCl + 100 ppm aniline, stable for 100 h',
        'PMS单独': 'PMS alone',
        'PUF + PMS': 'PUF + PMS',
        'CNT/PUF + PMS': 'CNT/PUF + PMS',
        'CoFe₂O₄@CNT/PUF + PMS + 光照': 'CoFe₂O₄@CNT/PUF + PMS + light',
        'CoFe₂O₄@CNT负载量5mg，PMS 0.5 mM，冷凝水': 'CoFe₂O₄@CNT loading 5 mg, PMS 0.5 mM, condensed water',
        'CoFe₂O₄@CNT负载量10mg，PMS 0.5 mM，冷凝水': 'CoFe₂O₄@CNT loading 10 mg, PMS 0.5 mM, condensed water',
        'CoFe₂O₄@CNT负载量20mg，PMS 0.5 mM，冷凝水': 'CoFe₂O₄@CNT loading 20 mg, PMS 0.5 mM, condensed water',
        'CoFe₂O₄:CNT质量比2%，PMS 0.5 mM，冷凝水': 'CoFe₂O₄:CNT mass ratio 2%, PMS 0.5 mM, condensed water',
        'CoFe₂O₄:CNT质量比2%，PMS 0.5 mM，原水': 'CoFe₂O₄:CNT mass ratio 2%, PMS 0.5 mM, raw water',
        'CoFe₂O₄:CNT质量比4%，PMS 0.5 mM，冷凝水': 'CoFe₂O₄:CNT mass ratio 4%, PMS 0.5 mM, condensed water',
        'CoFe₂O₄:CNT质量比4%，PMS 0.5 mM，原水': 'CoFe₂O₄:CNT mass ratio 4%, PMS 0.5 mM, raw water',
        'CoFe₂O₄:CNT质量比6%，PMS 0.5 mM，冷凝水': 'CoFe₂O₄:CNT mass ratio 6%, PMS 0.5 mM, condensed water',
        'CoFe₂O₄:CNT质量比8%，PMS 0.5 mM，冷凝水': 'CoFe₂O₄:CNT mass ratio 8%, PMS 0.5 mM, condensed water',
        'PMS浓度0.25 mM，冷凝水': 'PMS concentration 0.25 mM, condensed water',
        'PMS浓度0.5 mM，冷凝水': 'PMS concentration 0.5 mM, condensed water',
        'PMS浓度1 mM，冷凝水': 'PMS concentration 1 mM, condensed water',
        'PMS浓度1 mM，原水': 'PMS concentration 1 mM, raw water',
        'PMS浓度2 mM，冷凝水': 'PMS concentration 2 mM, condensed water',
        '初始pH=3，冷凝水': 'initial pH=3, condensed water',
        '初始pH=5，冷凝水': 'initial pH=5, condensed water',
        '初始pH=7，冷凝水': 'initial pH=7, condensed water',
        '初始pH=9，冷凝水': 'initial pH=9, condensed water',
        '初始pH=11，冷凝水': 'initial pH=11, condensed water',
        '无淬灭剂': 'no quencher',
        '添加MeOH淬灭剂': 'with MeOH quencher',
        '添加TBA淬灭剂': 'with TBA quencher',
        '添加p-BQ淬灭剂': 'with p-BQ quencher',
        '添加L-His淬灭剂': 'with L-His quencher',
        '初始浓度10 ppm，冷凝水': 'initial concentration 10 ppm, condensed water',
        '初始浓度20 ppm，冷凝水': 'initial concentration 20 ppm, condensed water',
        '初始浓度30 ppm，冷凝水': 'initial concentration 30 ppm, condensed water',
        '初始浓度40 ppm，冷凝水': 'initial concentration 40 ppm, condensed water',
        '初始浓度20 ppm，原水': 'initial concentration 20 ppm, raw water',
        '初始浓度30 ppm，原水': 'initial concentration 30 ppm, raw water',
        '初始浓度40 ppm，原水': 'initial concentration 40 ppm, raw water',
        '第1循环，冷凝水': 'Cycle 1, condensed water',
        '第2循环，冷凝水': 'Cycle 2, condensed water',
        '第3循环，冷凝水': 'Cycle 3, condensed water',
        '第4循环，冷凝水': 'Cycle 4, condensed water',
        '第5循环，冷凝水': 'Cycle 5, condensed water',
        '第1-5循环，原水': 'Cycles 1-5, raw water',
        '100 ppm苯胺，冷凝水': '100 ppm aniline, condensed water',
        '100 ppm NMP，冷凝水': '100 ppm NMP, condensed water',
        '100 ppm DMSO，冷凝水': '100 ppm DMSO, condensed water',
        '10 ppm RhB，原水': '10 ppm RhB, raw water',
        '10 ppm MO，原水': '10 ppm MO, raw water',
        '10 ppm MB，原水': '10 ppm MB, raw water',
        'MoS₂/Fe³⁺/PMS体系，单独30 ppm': 'MoS₂/Fe³⁺/PMS system, alone 30 ppm',
        'MoS₂/Fe³⁺/PMS体系，CST混合物(各10 ppm)': 'MoS₂/Fe³⁺/PMS system, CST mixture (each 10 ppm)',
        'MoS₂/Fe³⁺/PMS体系，S-T混合物(苯乙烯15 ppm + 甲苯15 ppm)': 'MoS₂/Fe³⁺/PMS system, S-T mixture (styrene 15 ppm + toluene 15 ppm)',
        'MoS₂/Fe³⁺/PMS体系，S-T混合物(苯乙烯10 ppm + 甲苯20 ppm)': 'MoS₂/Fe³⁺/PMS system, S-T mixture (styrene 10 ppm + toluene 20 ppm)',
        'MoS₂/Fe³⁺/PMS体系，S-T混合物(苯乙烯20 ppm + 甲苯10 ppm)': 'MoS₂/Fe³⁺/PMS system, S-T mixture (styrene 20 ppm + toluene 10 ppm)',
        'MoS₂/Fe³⁺/PMS体系，C-T混合物(氯苯15 ppm + 甲苯15 ppm)': 'MoS₂/Fe³⁺/PMS system, C-T mixture (chlorobenzene 15 ppm + toluene 15 ppm)',
        'MoS₂/Fe³⁺/PMS体系，C-T混合物(氯苯10 ppm + 甲苯20 ppm)': 'MoS₂/Fe³⁺/PMS system, C-T mixture (chlorobenzene 10 ppm + toluene 20 ppm)',
        'MoS₂/Fe³⁺/PMS体系，C-T混合物(氯苯20 ppm + 甲苯10 ppm)': 'MoS₂/Fe³⁺/PMS system, C-T mixture (chlorobenzene 20 ppm + toluene 10 ppm)',
        'Fe³⁺/PMS体系(无MoS₂)，S-T混合物(各15 ppm)': 'Fe³⁺/PMS system (without MoS₂), S-T mixture (each 15 ppm)',
        'Fe³⁺/PMS体系(无MoS₂)，C-T混合物(各15 ppm)': 'Fe³⁺/PMS system (without MoS₂), C-T mixture (each 15 ppm)',
        'MoS₂/Fe³⁺/PMS体系，S-T混合物(各15 ppm)，N₂饱和': 'MoS₂/Fe³⁺/PMS system, S-T mixture (each 15 ppm), N₂ saturated',
        'MoS₂/Fe³⁺/PMS体系，C-T混合物(各15 ppm)，N₂饱和': 'MoS₂/Fe³⁺/PMS system, C-T mixture (each 15 ppm), N₂ saturated',
        'MoS₂/Fe³⁺/PMS体系，S-T混合物(各15 ppm)，添加TBA': 'MoS₂/Fe³⁺/PMS system, S-T mixture (each 15 ppm), with TBA',
        'MoS₂/Fe³⁺/PMS体系，S-T混合物(各15 ppm)，添加EtOH': 'MoS₂/Fe³⁺/PMS system, S-T mixture (each 15 ppm), with EtOH',
        'MoS₂/Fe³⁺/PMS体系，S-T混合物(各15 ppm)，添加SOD': 'MoS₂/Fe³⁺/PMS system, S-T mixture (each 15 ppm), with SOD',
        'MoS₂/Fe³⁺/PMS体系，单独30 ppm，添加TBA': 'MoS₂/Fe³⁺/PMS system, alone 30 ppm, with TBA',
        'MoS₂/Fe³⁺/PMS体系，单独30 ppm，添加EtOH': 'MoS₂/Fe³⁺/PMS system, alone 30 ppm, with EtOH',
        'MoS₂/Fe³⁺/PMS体系，单独30 ppm，添加SOD': 'MoS₂/Fe³⁺/PMS system, alone 30 ppm, with SOD',
        '树皮填料(A)，启动期第5天(EBRT=105s，进气48ppm)': 'Bark packing (A), start-up day 5 (EBRT=105 s, inlet 48 ppm)',
        '空心多面球填料(B)，启动期第5天(EBRT=105s，进气48ppm)': 'Hollow polyhedral ball packing (B), start-up day 5 (EBRT=105 s, inlet 48 ppm)',
        '陶粒填料(C)，启动期第5天(EBRT=105s，进气48ppm)': 'Ceramsite packing (C), start-up day 5 (EBRT=105 s, inlet 48 ppm)',
        '自制复合填料(D)，启动期第5天(EBRT=105s，进气48ppm)': 'Self-made composite packing (D), start-up day 5 (EBRT=105 s, inlet 48 ppm)',
        '自制复合填料(D)，阶段III(EBRT=70s，进气384ppm)': 'Self-made composite packing (D), stage III (EBRT=70 s, inlet 384 ppm)',
        'PDVB@F1M3催化剂，PMS 3 g/L，连续氧化1小时': 'PDVB@F1M3 catalyst, PMS 3 g/L, continuous oxidation 1 h',
        'PDVB@F1M3催化剂，PMS 3 g/L，初始60分钟': 'PDVB@F1M3 catalyst, PMS 3 g/L, initial 60 min',
        'PDVB@F1M3催化剂，PMS 3 g/L，补充PMS后': 'PDVB@F1M3 catalyst, PMS 3 g/L, after PMS replenishment',
        'Fe-Mn氧化物涂层样品，一次“存储-降解”循环': 'Fe-Mn oxide coated sample, one "storage-degradation" cycle',
        'PDVB@F1M3催化剂，五次“存储-降解”循环': 'PDVB@F1M3 catalyst, five "storage-degradation" cycles',
        'PDVB@F1M3 + PMS，添加甲醇(MeOH)淬灭剂': 'PDVB@F1M3 + PMS, with methanol (MeOH) quencher',
        'PDVB@F1M3 + PMS，添加TEMP淬灭剂(淬灭¹O₂)': 'PDVB@F1M3 + PMS, with TEMP quencher (quenching ¹O₂)',
        'PDVB@F1M3 + PMS，添加AgNO₃电子捕获剂': 'PDVB@F1M3 + PMS, with AgNO₃ electron scavenger',
        '无硅油，多通道毛细管生物反应器，气体接触时间0.7秒，启动后15天': 'without silicone oil, multi-channel capillary bioreactor, gas contact time 0.7 s, 15 days after start-up',
        '添加5% (v/v) 硅油后2天，多通道毛细管生物反应器': '2 days after adding 5% (v/v) silicone oil, multi-channel capillary bioreactor',
        '添加10% (v/v) 硅油，多通道毛细管生物反应器': 'with 10% (v/v) silicone oil, multi-channel capillary bioreactor',
        '10%硅油，气体/液体比增加（第122天后），多通道毛细管生物反应器': '10% silicone oil, increased gas/liquid ratio (after day 122), multi-channel capillary bioreactor',
        '第158天，pH升至8.0，微藻存在下': 'Day 158, pH increased to 8.0, in the presence of microalgae',
        '第185天，pH升至约9.3，微藻存在下': 'Day 185, pH increased to about 9.3, in the presence of microalgae',
        'CC非生物阳极，开路，6 h': 'CC abiotic anode, open circuit, 6 h',
        'N-CNTs/CC非生物阳极，开路，6 h': 'N-CNTs/CC abiotic anode, open circuit, 6 h',
        'CC生物阳极，开路，6 h': 'CC bioanode, open circuit, 6 h',
        'N-CNTs/CC生物阳极，开路，6 h': 'N-CNTs/CC bioanode, open circuit, 6 h',
        'N-CNTs/CC生物阳极，闭路（0.4 V），6 h': 'N-CNTs/CC bioanode, closed circuit (0.4 V), 6 h',
        'N-CNTs/CC生物阳极，闭路（0.4 V），6 h，50 mg/L': 'N-CNTs/CC bioanode, closed circuit (0.4 V), 6 h, 50 mg/L',
        'N-CNTs/CC生物阳极，闭路（0.4 V），6 h，200 mg/L': 'N-CNTs/CC bioanode, closed circuit (0.4 V), 6 h, 200 mg/L',
        'N-CNTs/CC生物阳极，闭路（0.4 V），6 h，400 mg/L': 'N-CNTs/CC bioanode, closed circuit (0.4 V), 6 h, 400 mg/L',
        'N-CNTs/CC生物阳极，连续流，HRT=3 h': 'N-CNTs/CC bioanode, continuous flow, HRT=3 h',
        '单组分，闭路，1 h': 'single component, closed circuit, 1 h',
        '混合污染物（MT：MMA+甲苯），24 h': 'mixed pollutants (MT: MMA+toluene), 24 h',
        '混合污染物（MX：MMA+间二甲苯），24 h': 'mixed pollutants (MX: MMA+m-xylene), 24 h',
        '混合污染物（MTX：MMA+甲苯+间二甲苯），24 h': 'mixed pollutants (MTX: MMA+toluene+m-xylene), 24 h',
        '混合污染物（TX：甲苯+间二甲苯），24 h': 'mixed pollutants (TX: toluene+m-xylene), 24 h',
        'H2O2单独处理，时间100 min，H2O2 3 g/L': 'H2O2 alone treatment, time 100 min, H2O2 3 g/L',
        'UV单独处理，时间120 min，250 W Hg灯': 'UV alone treatment, time 120 min, 250 W Hg lamp',
        'UV+H2O2，时间150 min，H2O2 6 g/L': 'UV+H2O2, time 150 min, H2O2 6 g/L',
        '光Fenton，时间180 min，H2O2 1 g/L，FeSO4 0.1 g/L': 'photo-Fenton, time 180 min, H2O2 1 g/L, FeSO4 0.1 g/L',
        '光催化Fenton(UV/Fenton/TiO2)，时间180 min，H2O2 1 g/L，FeSO4 0.1 g/L，TiO2 100 mg/L': 'photocatalytic Fenton (UV/Fenton/TiO2), time 180 min, H2O2 1 g/L, FeSO4 0.1 g/L, TiO2 100 mg/L',
        '初始pH=2，温度60°C，BTEX浓度150 mg/L，H2O2 1.115 g/L，Fe²⁺ 0.11 g/L，TiO2 100 mg/L': 'initial pH=2, temperature 60°C, BTEX concentration 150 mg/L, H2O2 1.115 g/L, Fe²⁺ 0.11 g/L, TiO2 100 mg/L',
        '初始pH=3，其他同pH=2条件': 'initial pH=3, other conditions same as pH=2',
        '初始pH=4，其他同pH=2条件': 'initial pH=4, other conditions same as pH=2',
        '初始pH=5，其他同pH=2条件': 'initial pH=5, other conditions same as pH=2',
        '初始pH=6，其他同pH=2条件': 'initial pH=6, other conditions same as pH=2',
        '温度30°C，其他同30°C条件': 'temperature 30°C, other conditions same as 30°C',
        '温度40°C，其他同30°C条件': 'temperature 40°C, other conditions same as 30°C',
        '温度50°C，其他同30°C条件': 'temperature 50°C, other conditions same as 30°C',
        '温度60°C，其他同30°C条件': 'temperature 60°C, other conditions same as 30°C',
        '温度70°C，其他同30°C条件': 'temperature 70°C, other conditions same as 30°C',
        'BTEX浓度100 mg/L，其他同100 mg/L条件': 'BTEX concentration 100 mg/L, other conditions same as 100 mg/L',
        'BTEX浓度150 mg/L，其他同100 mg/L条件': 'BTEX concentration 150 mg/L, other conditions same as 100 mg/L',
        'BTEX浓度200 mg/L，其他同100 mg/L条件': 'BTEX concentration 200 mg/L, other conditions same as 100 mg/L',
        'BTEX浓度250 mg/L，其他同100 mg/L条件': 'BTEX concentration 250 mg/L, other conditions same as 100 mg/L',
        'BTEX浓度300 mg/L，其他同100 mg/L条件': 'BTEX concentration 300 mg/L, other conditions same as 100 mg/L',
        'H2O2 0.275 g/L，其他同0.275 g/L条件': 'H2O2 0.275 g/L, other conditions same as 0.275 g/L',
        'H2O2 0.555 g/L，其他同0.275 g/L条件': 'H2O2 0.555 g/L, other conditions same as 0.275 g/L',
        'H2O2 0.835 g/L，其他同0.275 g/L条件': 'H2O2 0.835 g/L, other conditions same as 0.275 g/L',
        'H2O2 1.115 g/L，其他同0.275 g/L条件': 'H2O2 1.115 g/L, other conditions same as 0.275 g/L',
        'H2O2 1.395 g/L，其他同0.275 g/L条件': 'H2O2 1.395 g/L, other conditions same as 0.275 g/L',
        '反应时间30 min，其他同30 min条件': 'reaction time 30 min, other conditions same as 30 min',
        '反应时间60 min，其他同30 min条件': 'reaction time 60 min, other conditions same as 30 min',
        '反应时间90 min，其他同30 min条件': 'reaction time 90 min, other conditions same as 30 min',
        '反应时间120 min，其他同30 min条件': 'reaction time 120 min, other conditions same as 30 min',
        '反应时间150 min，其他同30 min条件': 'reaction time 150 min, other conditions same as 30 min',
        '反应时间180 min，其他同30 min条件': 'reaction time 180 min, other conditions same as 30 min',
        'Fe²⁺ 0.025 g/L，其他同0.025 g/L条件': 'Fe²⁺ 0.025 g/L, other conditions same as 0.025 g/L',
        'Fe²⁺ 0.05 g/L，其他同0.025 g/L条件': 'Fe²⁺ 0.05 g/L, other conditions same as 0.025 g/L',
        'Fe²⁺ 0.085 g/L，其他同0.025 g/L条件': 'Fe²⁺ 0.085 g/L, other conditions same as 0.025 g/L',
        'Fe²⁺ 0.11 g/L，其他同0.025 g/L条件': 'Fe²⁺ 0.11 g/L, other conditions same as 0.025 g/L',
        'Fe²⁺ 0.19 g/L，其他同0.025 g/L条件': 'Fe²⁺ 0.19 g/L, other conditions same as 0.025 g/L',
        'TiO2 25 mg/L，其他同25 mg/L条件': 'TiO2 25 mg/L, other conditions same as 25 mg/L',
        'TiO2 50 mg/L，其他同25 mg/L条件': 'TiO2 50 mg/L, other conditions same as 25 mg/L',
        'TiO2 75 mg/L，其他同25 mg/L条件': 'TiO2 75 mg/L, other conditions same as 25 mg/L',
        'TiO2 100 mg/L，其他同25 mg/L条件': 'TiO2 100 mg/L, other conditions same as 25 mg/L',
        'TiO2 125 mg/L，其他同25 mg/L条件': 'TiO2 125 mg/L, other conditions same as 25 mg/L',
        'PBD实验1：初始pH=4，温度50°C，BTEX 200 mg/L，H2O2 0.835 g/L，时间150 min，Fe²⁺ 0.085 g/L，TiO2 125 mg/L': 'PBD experiment 1: initial pH=4, temperature 50°C, BTEX 200 mg/L, H2O2 0.835 g/L, time 150 min, Fe²⁺ 0.085 g/L, TiO2 125 mg/L',
        'PBD实验2：初始pH=4，温度70°C，BTEX 100 mg/L，H2O2 1.395 g/L，时间150 min，Fe²⁺ 0.085 g/L，TiO2 75 mg/L': 'PBD experiment 2: initial pH=4, temperature 70°C, BTEX 100 mg/L, H2O2 1.395 g/L, time 150 min, Fe²⁺ 0.085 g/L, TiO2 75 mg/L',
        'PBD实验3：初始pH=3，温度70°C，BTEX 200 mg/L，H2O2 0.835 g/L，时间210 min，Fe²⁺ 0.085 g/L，TiO2 75 mg/L': 'PBD experiment 3: initial pH=3, temperature 70°C, BTEX 200 mg/L, H2O2 0.835 g/L, time 210 min, Fe²⁺ 0.085 g/L, TiO2 75 mg/L',
        'PBD实验4：初始pH=4，温度50°C，BTEX 200 mg/L，H2O2 1.395 g/L，时间150 min，Fe²⁺ 0.197 g/L，TiO2 75 mg/L': 'PBD experiment 4: initial pH=4, temperature 50°C, BTEX 200 mg/L, H2O2 1.395 g/L, time 150 min, Fe²⁺ 0.197 g/L, TiO2 75 mg/L',
        'PBD实验5：初始pH=4，温度70°C，BTEX 100 mg/L，H2O2 1.395 g/L，时间210 min，Fe²⁺ 0.085 g/L，TiO2 75 mg/L': 'PBD experiment 5: initial pH=4, temperature 70°C, BTEX 100 mg/L, H2O2 1.395 g/L, time 210 min, Fe²⁺ 0.085 g/L, TiO2 75 mg/L',
        'PBD实验6：初始pH=4，温度70°C，BTEX 200 mg/L，H2O2 0.835 g/L，时间210 min，Fe²⁺ 0.197 g/L，TiO2 75 mg/L': 'PBD experiment 6: initial pH=4, temperature 70°C, BTEX 200 mg/L, H2O2 0.835 g/L, time 210 min, Fe²⁺ 0.197 g/L, TiO2 75 mg/L',
        'PBD实验7：初始pH=3，温度70°C，BTEX 200 mg/L，H2O2 1.395 g/L，时间150 min，Fe²⁺ 0.197 g/L，TiO2 125 mg/L': 'PBD experiment 7: initial pH=3, temperature 70°C, BTEX 200 mg/L, H2O2 1.395 g/L, time 150 min, Fe²⁺ 0.197 g/L, TiO2 125 mg/L',
        'PBD实验8：初始pH=2，温度50°C，BTEX 200 mg/L，H2O2 1.395 g/L，时间210 min，Fe²⁺ 0.085 g/L，TiO2 125 mg/L': 'PBD experiment 8: initial pH=2, temperature 50°C, BTEX 200 mg/L, H2O2 1.395 g/L, time 210 min, Fe²⁺ 0.085 g/L, TiO2 125 mg/L',
        'PBD实验9：初始pH=2，温度70°C，BTEX 100 mg/L，H2O2 1.395 g/L，时间210 min，Fe²⁺ 0.197 g/L，TiO2 125 mg/L': 'PBD experiment 9: initial pH=2, temperature 70°C, BTEX 100 mg/L, H2O2 1.395 g/L, time 210 min, Fe²⁺ 0.197 g/L, TiO2 125 mg/L',
        'PBD实验10：初始pH=4，温度50°C，BTEX 100 mg/L，H2O2 0.835 g/L，时间210 min，Fe²⁺ 0.197 g/L，TiO2 125 mg/L': 'PBD experiment 10: initial pH=4, temperature 50°C, BTEX 100 mg/L, H2O2 0.835 g/L, time 210 min, Fe²⁺ 0.197 g/L, TiO2 125 mg/L',
        'PBD实验11：初始pH=3，温度50°C，BTEX 100 mg/L，H2O2 0.835 g/L，时间150 min，Fe²⁺ 0.197 g/L，TiO2 125 mg/L': 'PBD experiment 11: initial pH=3, temperature 50°C, BTEX 100 mg/L, H2O2 0.835 g/L, time 150 min, Fe²⁺ 0.197 g/L, TiO2 125 mg/L',
        'PBD实验12：初始pH=2，温度50°C，BTEX 100 mg/L，H2O2 0.835 g/L，时间150 min，Fe²⁺ 0.085 g/L，TiO2 75 mg/L': 'PBD experiment 12: initial pH=2, temperature 50°C, BTEX 100 mg/L, H2O2 0.835 g/L, time 150 min, Fe²⁺ 0.085 g/L, TiO2 75 mg/L',
        'CCD实验1：初始pH=2，BTEX 100 mg/L，H2O2 0.835 g/L，TiO2 75 mg/L': 'CCD experiment 1: initial pH=2, BTEX 100 mg/L, H2O2 0.835 g/L, TiO2 75 mg/L',
        'CCD实验2：初始pH=4，BTEX 100 mg/L，H2O2 0.835 g/L，TiO2 75 mg/L': 'CCD experiment 2: initial pH=4, BTEX 100 mg/L, H2O2 0.835 g/L, TiO2 75 mg/L',
        'CCD实验3：初始pH=2，BTEX 200 mg/L，H2O2 0.835 g/L，TiO2 75 mg/L': 'CCD experiment 3: initial pH=2, BTEX 200 mg/L, H2O2 0.835 g/L, TiO2 75 mg/L',
        'CCD实验4：初始pH=4，BTEX 200 mg/L，H2O2 0.835 g/L，TiO2 75 mg/L': 'CCD experiment 4: initial pH=4, BTEX 200 mg/L, H2O2 0.835 g/L, TiO2 75 mg/L',
        'CCD实验5：初始pH=2，BTEX 100 mg/L，H2O2 1.395 g/L，TiO2 75 mg/L': 'CCD experiment 5: initial pH=2, BTEX 100 mg/L, H2O2 1.395 g/L, TiO2 75 mg/L',
        'CCD实验6：初始pH=4，BTEX 100 mg/L，H2O2 1.395 g/L，TiO2 75 mg/L': 'CCD experiment 6: initial pH=4, BTEX 100 mg/L, H2O2 1.395 g/L, TiO2 75 mg/L',
        'CCD实验7：初始pH=2，BTEX 200 mg/L，H2O2 1.395 g/L，TiO2 75 mg/L': 'CCD experiment 7: initial pH=2, BTEX 200 mg/L, H2O2 1.395 g/L, TiO2 75 mg/L',
        'CCD实验8：初始pH=4，BTEX 200 mg/L，H2O2 1.395 g/L，TiO2 75 mg/L': 'CCD experiment 8: initial pH=4, BTEX 200 mg/L, H2O2 1.395 g/L, TiO2 75 mg/L',
        'CCD实验9：初始pH=2，BTEX 100 mg/L，H2O2 0.835 g/L，TiO2 125 mg/L': 'CCD experiment 9: initial pH=2, BTEX 100 mg/L, H2O2 0.835 g/L, TiO2 125 mg/L',
        'CCD实验10：初始pH=4，BTEX 100 mg/L，H2O2 0.835 g/L，TiO2 125 mg/L': 'CCD experiment 10: initial pH=4, BTEX 100 mg/L, H2O2 0.835 g/L, TiO2 125 mg/L',
        'CCD实验11：初始pH=2，BTEX 200 mg/L，H2O2 0.835 g/L，TiO2 125 mg/L': 'CCD experiment 11: initial pH=2, BTEX 200 mg/L, H2O2 0.835 g/L, TiO2 125 mg/L',
        'CCD实验12：初始pH=4，BTEX 200 mg/L，H2O2 0.835 g/L，TiO2 125 mg/L': 'CCD experiment 12: initial pH=4, BTEX 200 mg/L, H2O2 0.835 g/L, TiO2 125 mg/L',
        'CCD实验13：初始pH=2，BTEX 100 mg/L，H2O2 1.395 g/L，TiO2 125 mg/L': 'CCD experiment 13: initial pH=2, BTEX 100 mg/L, H2O2 1.395 g/L, TiO2 125 mg/L',
        'CCD实验14：初始pH=4，BTEX 100 mg/L，H2O2 1.395 g/L，TiO2 125 mg/L': 'CCD experiment 14: initial pH=4, BTEX 100 mg/L, H2O2 1.395 g/L, TiO2 125 mg/L',
        'CCD实验15：初始pH=2，BTEX 200 mg/L，H2O2 1.395 g/L，TiO2 125 mg/L': 'CCD experiment 15: initial pH=2, BTEX 200 mg/L, H2O2 1.395 g/L, TiO2 125 mg/L',
        'CCD实验16：初始pH=4，BTEX 200 mg/L，H2O2 1.395 g/L，TiO2 125 mg/L': 'CCD experiment 16: initial pH=4, BTEX 200 mg/L, H2O2 1.395 g/L, TiO2 125 mg/L',
        'CCD实验17：初始pH=3，BTEX 150 mg/L，H2O2 1.115 g/L，TiO2 100 mg/L': 'CCD experiment 17: initial pH=3, BTEX 150 mg/L, H2O2 1.115 g/L, TiO2 100 mg/L',
        'CCD实验18：初始pH=3，BTEX 150 mg/L，H2O2 1.115 g/L，TiO2 100 mg/L (重复)': 'CCD experiment 18: initial pH=3, BTEX 150 mg/L, H2O2 1.115 g/L, TiO2 100 mg/L (replicate)',
        'CCD实验19：初始pH=3，BTEX 100 mg/L，H2O2 1.115 g/L，TiO2 100 mg/L': 'CCD experiment 19: initial pH=3, BTEX 100 mg/L, H2O2 1.115 g/L, TiO2 100 mg/L',
        'CCD实验20：初始pH=3，BTEX 200 mg/L，H2O2 1.115 g/L，TiO2 100 mg/L': 'CCD experiment 20: initial pH=3, BTEX 200 mg/L, H2O2 1.115 g/L, TiO2 100 mg/L',
        'CCD实验21：初始pH=3，BTEX 150 mg/L，H2O2 0.835 g/L，TiO2 100 mg/L': 'CCD experiment 21: initial pH=3, BTEX 150 mg/L, H2O2 0.835 g/L, TiO2 100 mg/L',
        'CCD实验22：初始pH=3，BTEX 150 mg/L，H2O2 1.395 g/L，TiO2 100 mg/L': 'CCD experiment 22: initial pH=3, BTEX 150 mg/L, H2O2 1.395 g/L, TiO2 100 mg/L',
        'CCD实验23：初始pH=3，BTEX 150 mg/L，H2O2 1.115 g/L，TiO2 75 mg/L': 'CCD experiment 23: initial pH=3, BTEX 150 mg/L, H2O2 1.115 g/L, TiO2 75 mg/L',
        'CCD实验24：初始pH=3，BTEX 150 mg/L，H2O2 1.115 g/L，TiO2 125 mg/L': 'CCD experiment 24: initial pH=3, BTEX 150 mg/L, H2O2 1.115 g/L, TiO2 125 mg/L',
        'CCD实验25-31：中心点重复7次，初始pH=3，BTEX 150 mg/L，H2O2 1.115 g/L，TiO2 100 mg/L': 'CCD experiments 25-31: center point repeated 7 times, initial pH=3, BTEX 150 mg/L, H2O2 1.115 g/L, TiO2 100 mg/L',
        '填料：玉米芯；微生物：活性污泥': 'Packing: corncob; microorganism: activated sludge',
        '填料：木炭；微生物：混合菌群': 'Packing: charcoal; microorganism: mixed culture',
        '填料：浮石/堆肥；微生物：混合菌群': 'Packing: pumice/compost; microorganism: mixed culture',
        '填料：堆肥；微生物：混合菌群': 'Packing: compost; microorganism: mixed culture',
        '填料：聚氨酯泡沫；微生物：混合菌群': 'Packing: polyurethane foam; microorganism: mixed culture',
        '填料：珍珠岩；微生物：炼油厂污泥混合菌群': 'Packing: perlite; microorganism: refinery sludge mixed culture',
        '电解辅助吸收(ELAA)，0.05 M Na₂SO₄，电流密度6 mA/cm²，气体流量6 L/h': 'Electrolysis-assisted absorption (ELAA), 0.05 M Na₂SO₄, current density 6 mA/cm², gas flow rate 6 L/h',
        '电-Fenton辅助吸收(EFAA)，0.05 M Na₂SO₄ + 0.5 mM Fe²⁺，pH 3，电流密度6 mA/cm²，气体流量6 L/h': 'Electro-Fenton assisted absorption (EFAA), 0.05 M Na₂SO₄ + 0.5 mM Fe²⁺, pH 3, current density 6 mA/cm², gas flow rate 6 L/h',
        'CaO2/Fe(II)/BTEX摩尔比5/5/1，超纯水，反应60 min': 'CaO2/Fe(II)/BTEX molar ratio 5/5/1, ultrapure water, reaction 60 min',
        'CaO2/Fe(II)/BTEX摩尔比10/10/1，超纯水，反应60 min': 'CaO2/Fe(II)/BTEX molar ratio 10/10/1, ultrapure water, reaction 60 min',
        'CaO2/Fe(II)/BTEX摩尔比20/20/1，超纯水，反应60 min': 'CaO2/Fe(II)/BTEX molar ratio 20/20/1, ultrapure water, reaction 60 min',
        'CaO2/Fe(II)/BTEX摩尔比5/5/1，实际地下水，反应60 min': 'CaO2/Fe(II)/BTEX molar ratio 5/5/1, actual groundwater, reaction 60 min',
        'CaO2/Fe(II)/BTEX摩尔比10/10/1，实际地下水，反应60 min': 'CaO2/Fe(II)/BTEX molar ratio 10/10/1, actual groundwater, reaction 60 min',
        'CaO2/Fe(II)/BTEX摩尔比20/20/1，实际地下水，反应60 min': 'CaO2/Fe(II)/BTEX molar ratio 20/20/1, actual groundwater, reaction 60 min',
        'CaO2/Fe(II)/BTEX摩尔比40/40/1，实际地下水，反应60 min': 'CaO2/Fe(II)/BTEX molar ratio 40/40/1, actual groundwater, reaction 60 min',
        'CaO2/Fe(II)/螯合剂/BTEX摩尔比10/10/20/1，实际地下水，无螯合剂': 'CaO2/Fe(II)/chelator/BTEX molar ratio 10/10/20/1, actual groundwater, without chelator',
        '添加柠檬酸(CA)': 'with citric acid (CA)',
        '添加谷氨酸(GA)': 'with glutamic acid (GA)',
        '添加草酸(OA)': 'with oxalic acid (OA)',
        'BTF-a，仅正己烷，稳定运行后': 'BTF-a, only n-hexane, after stable operation',
        'BTF-b，混合废气（正己烷+DCM+DMAC），第26天': 'BTF-b, mixed waste gas (n-hexane+DCM+DMAC), day 26',
        'BTF-b，正己烷100 mg/m³，DMAC 100 mg/L': 'BTF-b, n-hexane 100 mg/m³, DMAC 100 mg/L',
        'BTF-b，正己烷100 mg/m³，DMAC 500 mg/L': 'BTF-b, n-hexane 100 mg/m³, DMAC 500 mg/L',
        'BTF-b，正己烷300 mg/m³，DMAC 100 mg/L': 'BTF-b, n-hexane 300 mg/m³, DMAC 100 mg/L',
        'BTF-b，正己烷300 mg/m³，DMAC 500 mg/L': 'BTF-b, n-hexane 300 mg/m³, DMAC 500 mg/L',
        'BTF-b，正己烷500 mg/m³，DMAC 100 mg/L': 'BTF-b, n-hexane 500 mg/m³, DMAC 100 mg/L',
        'BTF-b，正己烷500 mg/m³，DMAC 500 mg/L': 'BTF-b, n-hexane 500 mg/m³, DMAC 500 mg/L',
        'BTF-b，正己烷100-500 mg/m³，DCM 750 mg/m³': 'BTF-b, n-hexane 100-500 mg/m³, DCM 750 mg/m³',
        'HRT 48 h，乙醇0.72 g/L，无回流（时期II）': 'HRT 48 h, ethanol 0.72 g/L, no recirculation (period II)',
        'HRT 36 h，乙醇0.76 g/L，无回流（时期III）': 'HRT 36 h, ethanol 0.76 g/L, no recirculation (period III)',
        'HRT 24 h，乙醇0.77 g/L，无回流（时期IV）': 'HRT 24 h, ethanol 0.77 g/L, no recirculation (period IV)',
        'HRT 48 h，乙醇0.76 g/L，回流0.7 L/h（时期V）': 'HRT 48 h, ethanol 0.76 g/L, recirculation 0.7 L/h (period V)',
        'HRT 48 h，乙醇0.11 g/L，回流0.7 L/h（时期VI）': 'HRT 48 h, ethanol 0.11 g/L, recirculation 0.7 L/h (period VI)',
        'HRT 48 h，乙醇0.10 g/L，无回流（时期VII）': 'HRT 48 h, ethanol 0.10 g/L, no recirculation (period VII)',
        '仅可见光照射': 'only visible light irradiation',
        '仅PMS': 'only PMS',
        'PMS+可见光': 'PMS + visible light',
        'Fe-CDs+可见光': 'Fe-CDs + visible light',
        'CDs+可见光': 'CDs + visible light',
        'CDs+PMS': 'CDs + PMS',
        'Fe-CDs+PMS': 'Fe-CDs + PMS',
        'Fe-CDs+PMS+可见光': 'Fe-CDs + PMS + visible light',
        'Fe-CDs 6 μg/L + PMS + 可见光': 'Fe-CDs 6 μg/L + PMS + visible light',
        'Fe-CDs 12 μg/L + PMS + 可见光': 'Fe-CDs 12 μg/L + PMS + visible light',
        'Fe-CDs 18 μg/L + PMS + 可见光': 'Fe-CDs 18 μg/L + PMS + visible light',
        'Fe-CDs + SPC + 可见光': 'Fe-CDs + SPC + visible light',
        'Fe-CDs + H₂O₂ + 可见光': 'Fe-CDs + H₂O₂ + visible light',
        'Fe-CDs + PDS + 可见光': 'Fe-CDs + PDS + visible light',
        'Fe-CDs + PMS + 可见光 + 10 mM NO₃⁻': 'Fe-CDs + PMS + visible light + 10 mM NO₃⁻',
        'Fe-CDs + PMS + 可见光 + 10 mM Cl⁻': 'Fe-CDs + PMS + visible light + 10 mM Cl⁻',
        'Fe-CDs + PMS + 可见光 + 10 mM SO₄²⁻': 'Fe-CDs + PMS + visible light + 10 mM SO₄²⁻',
        'Fe-CDs + PMS + 可见光 + 10 mM HCO₃⁻': 'Fe-CDs + PMS + visible light + 10 mM HCO₃⁻',
        'Fe-CDs + PMS + 可见光 + 10 mg/L 腐殖酸': 'Fe-CDs + PMS + visible light + 10 mg/L humic acid',
        'Fe-CDs + PMS + 可见光 + 10 mM EDTA-2Na': 'Fe-CDs + PMS + visible light + 10 mM EDTA-2Na',
        'Fe-CDs + PMS + 可见光 + 300 mM 甲醇': 'Fe-CDs + PMS + visible light + 300 mM methanol',
        'Fe-CDs + PMS + 可见光 + 200 mM 异丙醇': 'Fe-CDs + PMS + visible light + 200 mM isopropanol',
        'Fe-CDs + PMS + 可见光 + 20 mM NaN₃': 'Fe-CDs + PMS + visible light + 20 mM NaN₃',
        'Fe-CDs + PMS + 可见光 + 10 mM K₂Cr₂O₇': 'Fe-CDs + PMS + visible light + 10 mM K₂Cr₂O₇',
        'Fe-CDs + PMS + 可见光 + 10 mM 对苯醌': 'Fe-CDs + PMS + visible light + 10 mM p-benzoquinone'
    }
    # 替换
    for cn, en in replacements.items():
        text = text.replace(cn, en)
    # 处理剩余未覆盖的中文字符（简单保留原样，但可以尝试进一步清理）
    # 可选：去除中文标点等
    return text

# 应用转换
df['污染物类型_en'] = df['污染物类型'].apply(translate_pollutant)
df['营养条件_en'] = df['营养条件'].apply(translate_nutrient_condition)

# 删除原来的中文列（或保留，根据需求）
# 这里我们保留原列并新增英文列，或者直接替换。按用户要求，生成新表时这两列应为英文。
# 为了清晰，我们创建新DataFrame，包含所有原列，但用英文列替换原来的两列。
df_new = df.copy()
df_new['污染物类型'] = df['污染物类型_en']
df_new['营养条件'] = df['营养条件_en']
# 删除临时英文列
df_new.drop(columns=['污染物类型_en', '营养条件_en'], inplace=True)

# 保存为新的Excel文件
output_path = 'Pollutant_Experimental_Data_English.xlsx'
df_new.to_excel(output_path, index=False, sheet_name='Sheet1')

print(f"转换完成！新文件已保存为: {output_path}")
print(f"共处理 {len(df_new)} 行数据。")